default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: asrapi_development
  template: template0
  pool: 5
  timeout: 5000
  username: asrapi
  password: asrapi

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: asrapi_development
  template: template0
  pool: 5
  timeout: 5000
  username: asrapi
  password: asrapi

test:
  <<: *default
  database: db/test.sqlite3

#production:
  #host: localhost
  #adapter: postgresql
  #encoding: utf8
  #database: asrapi_production
  #template: template0
  #pool: 5
  #timeout: 5000
  #username: <%= ENV['ASRAPI_DATABASE_USER'] %>
  #password: <%= ENV['ASRAPI_DATABASE_PASSWORD'] %>
